export default {
  publicPath: "/",
  analytics: {
    ga: "",
    baidu: "",
  },
  favicon: "/favicon.png",
  title: "HZNU Online Judge",
  base: "/",
  metas: [
    {
      name: "keywords",
      content: "icpc, ccpc, online, judge",
    },
    {
      name: "description",
      content: "HZNU Online Judge",
    },
  ],
  apiEndpoint: "/",
  // api_proxy_target: "https://v3.hznuoj.com",
  api_proxy_target: "http://127.0.0.1:3000",
  monacoEditorSupportedLanguages: [
    "abap",
    "apex",
    "azcli",
    "bat",
    "cameligo",
    "clojure",
    "coffee",
    "cpp",
    "csharp",
    "csp",
    "css",
    "dart",
    "dockerfile",
    "fsharp",
    "go",
    "graphql",
    "handlebars",
    "hcl",
    "html",
    "ini",
    "java",
    "javascript",
    "json",
    "julia",
    "kotlin",
    "less",
    "lexon",
    "lua",
    "markdown",
    "mips",
    "msdax",
    "mysql",
    "objective-c",
    "pascal",
    "pascaligo",
    "perl",
    "pgsql",
    "php",
    "postiats",
    "powerquery",
    "powershell",
    "pug",
    "python",
    "r",
    "razor",
    "redis",
    "redshift",
    "restructuredtext",
    "ruby",
    "rust",
    "sb",
    "scala",
    "scheme",
    "scss",
    "shell",
    "solidity",
    "sophia",
    "sql",
    "st",
    "swift",
    "systemverilog",
    "tcl",
    "twig",
    "typescript",
    "vb",
    "xml",
    "yaml",
  ],
};
